### ISSUE TITLE
Create EditorOnly/PlayModeOnly/PrefabOnly Attribute

### ISSUE THREAD

**Issue by uurha** [techno-dwarf-works/better-attributes#7]
- [x] techno-dwarf-works/better-attributes-legacy#63
- [x] techno-dwarf-works/better-attributes-legacy#64
- [ ] techno-dwarf-works/better-attributes#6
